#!/bin/sh
set -eu

SEARXNG_CONFIG_DIR="${SEARXNG_CONFIG_DIR:-/etc/searxng}"
SEARXNG_BACKUP_OBJECT_KEY="${SEARXNG_BACKUP_OBJECT_KEY:-northflank2/searxng-config.tar.gz.enc}"
SEARXNG_BACKUP_PASSWORD="${SEARXNG_BACKUP_PASSWORD:-}"

if [ -z "$SEARXNG_BACKUP_PASSWORD" ]; then
  echo "[backup-searxng] SEARXNG_BACKUP_PASSWORD is required" >&2
  exit 1
fi

DATA_DIR="$SEARXNG_CONFIG_DIR" \
BACKUP_OBJECT_KEY="$SEARXNG_BACKUP_OBJECT_KEY" \
BACKUP_PASSWORD="$SEARXNG_BACKUP_PASSWORD" \
BACKUP_INPUT_FILE="/tmp/backup-searxng-${SEARXNG_BACKUP_OBJECT_KEY##*/}" \
backup-data
