CREATE SCHEMA IF NOT EXISTS okx_research;
CREATE TABLE IF NOT EXISTS okx_research.storage_meta (key text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS okx_research.auth_meta (key text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS okx_research.auth_sessions (
  token_hash text PRIMARY KEY,
  csrf_token text NOT NULL,
  created_at bigint NOT NULL,
  expires_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS okx_auth_expiry ON okx_research.auth_sessions(expires_at);
CREATE INDEX IF NOT EXISTS okx_auth_created ON okx_research.auth_sessions(created_at);
CREATE TABLE IF NOT EXISTS okx_research.research_meta (key text PRIMARY KEY, value text NOT NULL);
CREATE TABLE IF NOT EXISTS okx_research.lifecycle_positions (
  sub_pos_id text PRIMARY KEY,
  unique_code text NOT NULL,
  inst_id text NOT NULL,
  pos_side text NOT NULL,
  state text NOT NULL,
  first_seen_at bigint NOT NULL,
  last_seen_at bigint NOT NULL,
  opened_at bigint NOT NULL,
  closed_at bigint,
  open_avg_px text NOT NULL,
  last_mark_px text NOT NULL,
  quantity text NOT NULL,
  last_upl text NOT NULL,
  last_upl_ratio text NOT NULL,
  miss_count integer NOT NULL DEFAULT 0,
  last_snapshot_at bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS okx_research.lifecycle_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sub_pos_id text NOT NULL REFERENCES okx_research.lifecycle_positions(sub_pos_id),
  event_type text NOT NULL,
  observed_at bigint NOT NULL,
  detail_json text NOT NULL
);
CREATE TABLE IF NOT EXISTS okx_research.position_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sub_pos_id text NOT NULL REFERENCES okx_research.lifecycle_positions(sub_pos_id),
  observed_at bigint NOT NULL,
  mark_px text NOT NULL,
  quantity text NOT NULL,
  upl text NOT NULL,
  upl_ratio text NOT NULL,
  UNIQUE(sub_pos_id, observed_at)
);
CREATE INDEX IF NOT EXISTS okx_events_position_time ON okx_research.lifecycle_events(sub_pos_id, observed_at);
CREATE INDEX IF NOT EXISTS okx_snapshots_position_time ON okx_research.position_snapshots(sub_pos_id, observed_at);
CREATE INDEX IF NOT EXISTS okx_positions_state_seen ON okx_research.lifecycle_positions(state, last_seen_at DESC);
