#!/bin/sh
set -eu

SEARXNG_CONFIG_DIR="${SEARXNG_CONFIG_DIR:-/etc/searxng}"
SEARXNG_BACKUP_OBJECT_KEY="${SEARXNG_BACKUP_OBJECT_KEY:-northflank2/searxng-config.tar.gz.enc}"
SEARXNG_BACKUP_PASSWORD="${SEARXNG_BACKUP_PASSWORD:-}"
SEARXNG_RESTORE_IF_DATA_EXISTS="${SEARXNG_RESTORE_IF_DATA_EXISTS:-false}"

if [ -z "$SEARXNG_BACKUP_PASSWORD" ]; then
  echo "[restore-searxng] SEARXNG_BACKUP_PASSWORD is not set; skipping restore"
  exit 0
fi

DATA_DIR="$SEARXNG_CONFIG_DIR" \
BACKUP_OBJECT_KEY="$SEARXNG_BACKUP_OBJECT_KEY" \
BACKUP_PASSWORD="$SEARXNG_BACKUP_PASSWORD" \
BACKUP_INPUT_FILE="/tmp/restore-searxng-${SEARXNG_BACKUP_OBJECT_KEY##*/}" \
RESTORE_IF_DATA_EXISTS="$SEARXNG_RESTORE_IF_DATA_EXISTS" \
restore-data
